### ISSUE TITLE
Make new issues from the requirements and use cases doc

### ISSUE THREAD

**Issue by philipkershaw** [cedadev/ceda-keycloak-theme#2]
Review requirement document against test version of keyclock

Review doc:
https://docs.google.com/document/d/1kCpTzC2CRnWNcbwiIuc2EsSIPszUO-bqJFeaecxmdtE/edit#  

test keycloak instance:
 
https://auth-test.ceda.ac.uk/auth/admin/ceda/console/

**Comment by spepler** [comment]
Been through the user portal cases for keycloak.
